## FIT5196 Task 1 in Assessment 1

### Student Name: Zhiqing Shu
### Student ID: 28217551

#### Date: 24/03/2018

Version: 2.0

Environment: Python 3.6.4 and Anaconda 5.1.0 (64-bit)

Libraries used: 

- pandas 0.22.0 (for dataframe, included in Anaconda Python 3.6)
- numpy 1.14.0 (for numpy array, included in Anaconda Python 3.6)

## 1. Introduction

This task is to extract the Basic Indicators table from an Excel file, **basic_indicators.xlsx**, and save the table in a CSV file as where the first column contains 202 country names, and the following 14 columns contain the different types of indicators.

The detailed requirements of this task is as the following:
- correctly parse and extract the table;
- existing Python packages can be used;
- it is not required to extract the column labels. Except for the first column, which should be named with "Country Name", the other columns should be indexed with integers(e.g.1,2,3...13);
- script must be written in a Jupyter notebook named as **"excel.ipynb"**;
- and the extracted data must be saved in a CSV file named as **"basic_indicators.csv"**;
- the input file must only be **"basic_indicators.xlsx"**.

## 2. Import libraries

In [1]:
import pandas as pd #parsing Excel file with Pandas
import numpy as np

## 3. Parse Excel File

As a first step, loading the Excel file as a Pandas `ExcelFile` [object](http://pandas.pydata.org/pandas-docs/stable/io.html#io-excel-reader) into Python.

In [2]:
excel_data = pd.ExcelFile('basic_indicators.xlsx')
excel_data

Viewing all the sheets we have in the Excel file by their names.

In [3]:
excel_data.sheet_names

['Basic Indicators']

There is only one sheet contained in the Excel file, so we just need to read this worksheet into a Pandas DataFrame and view it.

In [4]:
df = excel_data.parse('Basic Indicators')
df
#df.head()

,Unnamed: 0,TABLE 1. BASIC INDICATORS,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Countries and areas,Under–5 mortality rank,Under–5 mortality rate,NaN,Under–5 mortality rate by sex\n2016,NaN,Infant mortality rate (under 1),NaN,Neonatal mortality rate,...,Total adult literacy rate (%),NaN,Primary school net enrolment ratio ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,1990,2016,male,female,1990,2016,2016,...,2011−2016*,NaN,2011−2016*,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,NaN,Afghanistan,25,177,70,74,66,120,53,40,...,31.7411,NaN,–,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Albania,114,40,14,15,12,35,12,6,...,97.247,NaN,95.5173,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Algeria,78,49,25,27,24,41,22,16,...,75.136,x,97.0622,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Andorra,179,9,3,3,3,7,2,1,...,100,NaN,–,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Angola,17,221,83,88,76,131,55,29,...,66.0301,NaN,84.0123,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Anguilla,–,–,–,–,–,–,–,–,...,–,NaN,–,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Antigua and Barbuda,133,26,9,9,8,25,5,4,...,98.95,x,87.0461,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Argentina,126,29,11,12,10,26,10,6,...,98.09,NaN,99.3468,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Armenia,118,50,13,15,12,42,12,7,...,99.7444,NaN,96.0743,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Australia,164,9,4,4,3,8,3,2,...,–,NaN,97.0328,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Austria,164,10,4,4,3,8,3,2,...,–,NaN,–,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Azerbaijan,68,95,31,34,28,75,27,18,...,99.7901,NaN,94.1427,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Bahamas,126,24,11,11,10,20,9,6,...,–,NaN,97.5202,x,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Bahrain,142,23,8,8,7,20,7,3,...,94.5568,x,96.4285,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Bangladesh,62,144,34,37,32,100,28,20,...,72.7587,NaN,90.5086,x,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Barbados,123,18,12,13,11,16,11,8,...,–,NaN,91.0225,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Belarus,164,15,4,4,3,12,3,2,...,99.6171,x,95.3602,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,Belgium,164,10,4,4,4,8,3,2,...,–,NaN,98.9478,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,Belize,106,39,15,16,13,32,13,10,...,–,NaN,96.1412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Benin,7,178,98,102,93,107,63,31,...,32.9488,NaN,95.8666,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Bhutan,66,128,32,36,29,90,27,18,...,57.0336,NaN,85.5824,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,...,92.4551,NaN,88.4827,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,Bosnia and Herzegovina,153,18,6,7,5,16,5,5,...,96.9918,NaN,–,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Botswana,56,54,41,44,37,42,33,26,...,81.1887,x,91.0209,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Brazil,106,64,15,16,14,53,14,8,...,91.7294,NaN,92.6971,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,British Virgin Islands,–,–,–,–,–,–,–,–,...,–,NaN,–,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,NaN,South Asia,–,129,48,48,48,92,39,28.2,...,67.6395,NaN,89.8002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,NaN,Sub-Saharan Africa,–,181,78,84,73,108,53,27.7,...,65.4588,NaN,80.2069,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,NaN,Eastern and Southern Africa,–,164,61,66,56,101,43,24.5,...,75.2131,NaN,81.6126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,NaN,West and Central Africa,–,199,95,101,89,116,63,30.8,...,–,NaN,–,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,NaN,Least developed countries,–,176,68,73,63,109,48,26.4,...,62.9906,NaN,80.6698,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,NaN,World,–,93,41,43,39,65,31,18.6,...,78.4088,NaN,90,**,NaN,NaN,NaN,NaN,NaN,NaN
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,NaN,For a complete list of countries and areas in ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,NaN,It is not advisable to compare data from conse...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,NaN,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,NaN,– Data not available.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,NaN,x Data refer to years or periods other than th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,NaN,* Data refer to the most recent year available...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,NaN,** Excludes China.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,NaN,Definitions of the indicators:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,NaN,Under-5 mortality rate – Probability of dying ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,NaN,Infant mortality rate – Probability of dying b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,NaN,Neonatal mortality rate – Probability of dying...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,NaN,Life expectancy at birth – Number of years new...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,NaN,Total adult literacy rate – Percentage of popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,NaN,Primary school net enrolment ratio – Number of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,NaN,Main data sources:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,NaN,"Under-5, infant and neonatal mortality rates –...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,NaN,Total population and births – United Nations P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,NaN,Under-five deaths – United Nations Inter-agenc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,NaN,Life expectancy at birth – United Nations Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,NaN,Total adult literacy rate and primary school e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

By observing the DataFrame, we can notice that the loaded data table is quite messy. 
The messiness includes:
- Rows only contain missing values that are indicated by NaN in Pandas DataFrame.
- Some column heads spread over multiple rows.
- Notes shown in the original Excel file appear in rows towards the end of the data frame.

In order to deal with the messiness, we need to remove all the rows and columns that are empty (i.e., only contains NaNs) by `dropna()`[function](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dropna.html) at first.

In [5]:
df = df.dropna(0, how = 'all')
df = df.dropna(1, how = 'all')
df

,TABLE 1. BASIC INDICATORS,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 23
1,Countries and areas,Under–5 mortality rank,Under–5 mortality rate,NaN,Under–5 mortality rate by sex\n2016,NaN,Infant mortality rate (under 1),NaN,Neonatal mortality rate,Total population (thousands),Annual number of births (thousands),Annual number of under–5 deaths (thousands),Life expectancy at birth (years),Total adult literacy rate (%),NaN,Primary school net enrolment ratio ...,NaN,NaN
2,NaN,NaN,1990,2016,male,female,1990,2016,2016,2016,2016,2016,2016,2011−2016*,NaN,2011−2016*,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,Afghanistan,25,177,70,74,66,120,53,40,34656,1142.96,80,63.673,31.7411,NaN,–,NaN,NaN
5,Albania,114,40,14,15,12,35,12,6,2926.35,34.75,0,78.345,97.247,NaN,95.5173,NaN,NaN
6,Algeria,78,49,25,27,24,41,22,16,40606.1,949.277,24,76.078,75.136,x,97.0622,NaN,NaN
7,Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,NaN,–,NaN,NaN
8,Angola,17,221,83,88,76,131,55,29,28813.5,1180.97,96,61.547,66.0301,NaN,84.0123,NaN,NaN
9,Anguilla,–,–,–,–,–,–,–,–,14.764,–,–,–,–,NaN,–,NaN,NaN
10,Antigua and Barbuda,133,26,9,9,8,25,5,4,100.963,1.636,0,76.364,98.95,x,87.0461,NaN,NaN
11,Argentina,126,29,11,12,10,26,10,6,43847.4,753.646,8,76.577,98.09,NaN,99.3468,NaN,NaN
12,Armenia,118,50,13,15,12,42,12,7,2924.82,40.158,1,74.618,99.7444,NaN,96.0743,NaN,NaN
13,Australia,164,9,4,4,3,8,3,2,24125.8,310.703,1,82.896,–,NaN,97.0328,NaN,NaN
14,Austria,164,10,4,4,3,8,3,2,8712.14,83.099,0,81.594,–,NaN,–,NaN,NaN
15,Azerbaijan,68,95,31,34,28,75,27,18,9725.38,176.026,5,72.026,99.7901,NaN,94.1427,NaN,NaN
16,Bahamas,126,24,11,11,10,20,9,6,391.232,5.57,0,75.675,–,NaN,97.5202,x,NaN
17,Bahrain,142,23,8,8,7,20,7,3,1425.17,21.489,0,76.9,94.5568,x,96.4285,NaN,NaN
18,Bangladesh,62,144,34,37,32,100,28,20,162952,3109.72,106,72.489,72.7587,NaN,90.5086,x,NaN
19,Barbados,123,18,12,13,11,16,11,8,284.996,3.408,0,75.906,–,NaN,91.0225,NaN,NaN
20,Belarus,164,15,4,4,3,12,3,2,9480.04,114.344,0,72.926,99.6171,x,95.3602,NaN,NaN
21,Belgium,164,10,4,4,4,8,3,2,11358.4,128.957,1,81.134,–,NaN,98.9478,NaN,NaN
22,Belize,106,39,15,16,13,32,13,10,366.954,8.181,0,70.384,–,NaN,96.1412,NaN,NaN
23,Benin,7,178,98,102,93,107,63,31,10872.3,396.613,38,60.907,32.9488,NaN,95.8666,NaN,NaN
24,Bhutan,66,128,32,36,29,90,27,18,797.765,14.528,0,70.197,57.0336,NaN,85.5824,NaN,NaN
25,Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,10887.9,252.768,9,69.125,92.4551,NaN,88.4827,NaN,NaN
26,Bosnia and Herzegovina,153,18,6,7,5,16,5,5,3516.82,32.523,0,76.911,96.9918,NaN,–,NaN,NaN
27,Botswana,56,54,41,44,37,42,33,26,2250.26,53.332,2,66.797,81.1887,x,91.0209,NaN,NaN
28,Brazil,106,64,15,16,14,53,14,8,207653,2965.62,45,75.509,91.7294,NaN,92.6971,NaN,NaN
29,British Virgin Islands,–,–,–,–,–,–,–,–,30.661,–,–,–,–,NaN,–,NaN,NaN
30,Brunei Darussalam,131,13,10,11,9,10,9,4,423.196,6.73,0,77.203,96.0856,NaN,–,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,Western Europe,–,11,4,4,4,9,3,2.3,491247,4947.65,19,81.3337,–,NaN,98.2646,NaN,NaN
212,Latin America and Caribbean,–,55,18,19,16,44,15,9.2,633773,10748.9,187,75.5157,93.5486,NaN,93.191,NaN,NaN
213,Middle East and North Africa,–,66,24,26,22,50,20,13.6,435225,9952.54,237,73.5015,77.7185,NaN,94.0352,NaN,NaN
214,North America,–,11,6,7,6,9,6,3.7,358469,4389.25,28,79.6939,–,NaN,94.2348,NaN,NaN
215,South Asia,–,129,48,48,48,92,39,28.2,1.76599e+06,35853.3,1713,68.709,67.6395,NaN,89.8002,NaN,NaN
216,Sub-Saharan Africa,–,181,78,84,73,108,53,27.7,1.03415e+06,37038.5,2860,60.397,65.4588,NaN,80.2069,NaN,NaN
217,Eastern and Southern Africa,–,164,61,66,56,101,43,24.5,542206,18203,1104,63.3639,75.2131,NaN,81.6126,NaN,NaN
218,West and Central Africa,–,199,95,101,89,116,63,30.8,491947,18835.5,1756,57.1271,–,NaN,–,NaN,NaN
219,Least developed countries,–,176,68,73,63,109,48,26.4,979388,31163.1,2101,64.4452,62.9906,NaN,80.6698,NaN,NaN
220,World,–,93,41,43,39,65,31,18.6,7.42726e+06,140462,5642,72.0404,78.4088,NaN,90,**,NaN
222,For a complete list of countries and areas in ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,It is not advisable to compare data from conse...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,– Data not available.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,x Data refer to years or periods other than th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,* Data refer to the most recent year available...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,** Excludes China.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,Definitions of the indicators:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,Under-5 mortality rate – Probability of dying ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,Infant mortality rate – Probability of dying b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,Neonatal mortality rate – Probability of dying...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,Life expectancy at birth – Number of years new...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,Total adult literacy rate – Percentage of popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,Primary school net enrolment ratio – Number of...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,Main data sources:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,"Under-5, infant and neonatal mortality rates –...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,Total population and births – United Nations P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,Under-five deaths – United Nations Inter-agenc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,Life expectancy at birth – United Nations Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,Total adult literacy rate and primary school e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The data we want starts from row index 3 and the last 34 rows are the notes in the original Excal file which are unnecessary. Therefore, we need to delete the first 3 rows and the last 34 rows.

In [6]:
# Delete the first 3 rows
df = df.drop(df.index[:3])
# Delete the last 34 rows
df = df.drop(df.index[-34:])
df

,TABLE 1. BASIC INDICATORS,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 23
4,Afghanistan,25,177,70,74,66,120,53,40,34656,1142.96,80,63.673,31.7411,NaN,–,NaN,NaN
5,Albania,114,40,14,15,12,35,12,6,2926.35,34.75,0,78.345,97.247,NaN,95.5173,NaN,NaN
6,Algeria,78,49,25,27,24,41,22,16,40606.1,949.277,24,76.078,75.136,x,97.0622,NaN,NaN
7,Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,NaN,–,NaN,NaN
8,Angola,17,221,83,88,76,131,55,29,28813.5,1180.97,96,61.547,66.0301,NaN,84.0123,NaN,NaN
9,Anguilla,–,–,–,–,–,–,–,–,14.764,–,–,–,–,NaN,–,NaN,NaN
10,Antigua and Barbuda,133,26,9,9,8,25,5,4,100.963,1.636,0,76.364,98.95,x,87.0461,NaN,NaN
11,Argentina,126,29,11,12,10,26,10,6,43847.4,753.646,8,76.577,98.09,NaN,99.3468,NaN,NaN
12,Armenia,118,50,13,15,12,42,12,7,2924.82,40.158,1,74.618,99.7444,NaN,96.0743,NaN,NaN
13,Australia,164,9,4,4,3,8,3,2,24125.8,310.703,1,82.896,–,NaN,97.0328,NaN,NaN
14,Austria,164,10,4,4,3,8,3,2,8712.14,83.099,0,81.594,–,NaN,–,NaN,NaN
15,Azerbaijan,68,95,31,34,28,75,27,18,9725.38,176.026,5,72.026,99.7901,NaN,94.1427,NaN,NaN
16,Bahamas,126,24,11,11,10,20,9,6,391.232,5.57,0,75.675,–,NaN,97.5202,x,NaN
17,Bahrain,142,23,8,8,7,20,7,3,1425.17,21.489,0,76.9,94.5568,x,96.4285,NaN,NaN
18,Bangladesh,62,144,34,37,32,100,28,20,162952,3109.72,106,72.489,72.7587,NaN,90.5086,x,NaN
19,Barbados,123,18,12,13,11,16,11,8,284.996,3.408,0,75.906,–,NaN,91.0225,NaN,NaN
20,Belarus,164,15,4,4,3,12,3,2,9480.04,114.344,0,72.926,99.6171,x,95.3602,NaN,NaN
21,Belgium,164,10,4,4,4,8,3,2,11358.4,128.957,1,81.134,–,NaN,98.9478,NaN,NaN
22,Belize,106,39,15,16,13,32,13,10,366.954,8.181,0,70.384,–,NaN,96.1412,NaN,NaN
23,Benin,7,178,98,102,93,107,63,31,10872.3,396.613,38,60.907,32.9488,NaN,95.8666,NaN,NaN
24,Bhutan,66,128,32,36,29,90,27,18,797.765,14.528,0,70.197,57.0336,NaN,85.5824,NaN,NaN
25,Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,10887.9,252.768,9,69.125,92.4551,NaN,88.4827,NaN,NaN
26,Bosnia and Herzegovina,153,18,6,7,5,16,5,5,3516.82,32.523,0,76.911,96.9918,NaN,–,NaN,NaN
27,Botswana,56,54,41,44,37,42,33,26,2250.26,53.332,2,66.797,81.1887,x,91.0209,NaN,NaN
28,Brazil,106,64,15,16,14,53,14,8,207653,2965.62,45,75.509,91.7294,NaN,92.6971,NaN,NaN
29,British Virgin Islands,–,–,–,–,–,–,–,–,30.661,–,–,–,–,NaN,–,NaN,NaN
30,Brunei Darussalam,131,13,10,11,9,10,9,4,423.196,6.73,0,77.203,96.0856,NaN,–,NaN,NaN
31,Bulgaria,142,18,8,8,7,15,7,4,7131.49,66.913,1,74.749,98.3525,NaN,93.3048,NaN,NaN
32,Burkina Faso,16,199,85,89,80,99,53,26,18646.4,715.598,60,60.361,34.5994,NaN,69.0963,NaN,NaN
33,Burundi,23,170,72,77,66,103,48,24,10524.1,437.227,31,57.481,61.5697,NaN,94.1483,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,Sweden,179,7,3,3,3,6,2,2,9837.53,118.513,0,82.462,–,NaN,99.3731,NaN,NaN
177,Switzerland,164,8,4,4,4,7,4,3,8401.74,86.328,0,83.308,–,NaN,93.3163,NaN,NaN
178,Syrian Arab Republic,95,37,18,19,16,30,14,9,18430.5,426.666,7,70.31,80.8445,x,66.6641,NaN,NaN
179,Tajikistan,53,107,43,48,38,84,37,20,8734.95,250.673,11,71.051,99.4507,x,97.7278,NaN,NaN
180,Thailand,123,38,12,14,11,31,11,7,68863.5,725.666,9,75.303,92.8683,NaN,90.7559,NaN,NaN
181,The former Yugoslav Republic of Macedonia,123,37,12,13,11,34,11,8,2081.21,23.493,0,75.703,96.1289,x,91.0574,NaN,NaN
182,Timor–Leste,46,175,50,54,46,132,42,22,1268.67,44.03,2,68.881,58.309,x,95.5923,NaN,NaN
183,Togo,21,145,76,82,70,89,51,26,7606.37,256.286,19,60.232,63.7456,NaN,95.4313,NaN,NaN
184,Tokelau,–,–,–,–,–,–,–,–,1.282,–,–,–,–,NaN,–,NaN,NaN
185,Tonga,100,22,16,15,18,19,14,7,107.122,2.607,0,73.029,99.3855,NaN,88.2331,NaN,NaN
186,Trinidad and Tobago,92,30,19,20,17,26,17,13,1364.96,18.951,0,70.673,–,NaN,95.2379,x,NaN
187,Tunisia,114,57,14,15,12,44,12,8,11403.2,210.021,3,75.731,79.0364,NaN,98.5652,NaN,NaN
188,Turkey,118,74,13,13,12,56,11,7,79512.4,1294.09,16,75.755,95.6014,NaN,94.1381,NaN,NaN
189,Turkmenistan,44,86,51,60,42,70,43,22,5662.54,144.35,7,67.835,–,NaN,–,NaN,NaN
190,Turks and Caicos Islands,–,–,–,–,–,–,–,–,34.9,–,–,–,–,NaN,–,NaN,NaN
191,Tuvalu,78,57,25,28,23,44,21,17,11.097,–,0,–,–,NaN,84.4011,NaN,NaN
192,Uganda,43,175,53,58,48,104,38,21,41488,1715.49,90,59.889,70.1982,NaN,93.6503,NaN,NaN
193,Ukraine,133,19,9,10,8,17,8,5,44438.6,479.168,4,71.96,99.9744,NaN,96.1755,NaN,NaN
194,United Arab Emirates,142,17,8,9,7,14,7,4,9269.61,91.583,1,77.256,90.0339,x,93.375,NaN,NaN
195,United Kingdom,164,9,4,5,4,8,4,3,65788.6,805.499,3,81.565,–,NaN,99.8543,NaN,NaN
196,United Republic of Tanzania,36,179,57,60,53,108,40,22,55572.2,2086.73,117,65.675,77.8872,NaN,80.0905,NaN,NaN
197,United States,151,11,7,7,6,9,6,4,322180,4002.52,26,79.392,–,NaN,93.7542,NaN,NaN
198,Uruguay,133,23,9,10,8,21,8,5,3444.01,48.546,0,77.493,98.5239,NaN,94.2177,NaN,NaN
199,Uzbekistan,80,72,24,27,21,59,21,14,31446.8,663.073,16,71.314,99.9838,NaN,94.6949,NaN,NaN
200,Vanuatu,73,36,28,30,25,29,23,12,270.402,6.93,0,72.133,74,x,85.8138,NaN,NaN
201,Venezuela (Bolivarian Republic of),100,30,16,18,15,25,14,10,31568.2,602.103,10,74.545,97.1271,NaN,89.8568,NaN,NaN
202,Viet Nam,82,51,22,25,18,37,17,12,94569.1,1581.76,34,76.253,93.5204,x,97.9651,NaN,NaN
203,Yemen,38,126,55,59,51,88,43,27,27584.2,867.303,48,64.953,–,NaN,84.8373,NaN,NaN
204,Zambia,33,182,63,68,58,110,44,23,16591.4,620.261,39,61.874,83.0077,x,87.4041,NaN,NaN
205,Zimbabwe,37,75,56,62,51,50,40,23,16150.4,535.37,30,61.163,88.6934,NaN,85.8624,NaN,NaN

After deleting useless rows and all the rows and columns that are empty, we can notice that there are still several columns containing NaN data. However, by carefully watching these cloumns, we can find **x**, refering to the notes of Excel file "x Data refer to years or periods other than those specified in the column heading. Such data are not included in the calculation of regional and global averages, with the exception of 2005–2006 data from India. Estimates from data years prior to 2000 are not displayed." , the **x** can be reatined if required, but according to the sample figure provided, we don't need to keep it, so we can just remove these columns.

In [7]:
df = df.drop(['Unnamed: 15','Unnamed: 17','Unnamed: 23'],1)
df

,TABLE 1. BASIC INDICATORS,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 16
4,Afghanistan,25,177,70,74,66,120,53,40,34656,1142.96,80,63.673,31.7411,–
5,Albania,114,40,14,15,12,35,12,6,2926.35,34.75,0,78.345,97.247,95.5173
6,Algeria,78,49,25,27,24,41,22,16,40606.1,949.277,24,76.078,75.136,97.0622
7,Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,–
8,Angola,17,221,83,88,76,131,55,29,28813.5,1180.97,96,61.547,66.0301,84.0123
9,Anguilla,–,–,–,–,–,–,–,–,14.764,–,–,–,–,–
10,Antigua and Barbuda,133,26,9,9,8,25,5,4,100.963,1.636,0,76.364,98.95,87.0461
11,Argentina,126,29,11,12,10,26,10,6,43847.4,753.646,8,76.577,98.09,99.3468
12,Armenia,118,50,13,15,12,42,12,7,2924.82,40.158,1,74.618,99.7444,96.0743
13,Australia,164,9,4,4,3,8,3,2,24125.8,310.703,1,82.896,–,97.0328
14,Austria,164,10,4,4,3,8,3,2,8712.14,83.099,0,81.594,–,–
15,Azerbaijan,68,95,31,34,28,75,27,18,9725.38,176.026,5,72.026,99.7901,94.1427
16,Bahamas,126,24,11,11,10,20,9,6,391.232,5.57,0,75.675,–,97.5202
17,Bahrain,142,23,8,8,7,20,7,3,1425.17,21.489,0,76.9,94.5568,96.4285
18,Bangladesh,62,144,34,37,32,100,28,20,162952,3109.72,106,72.489,72.7587,90.5086
19,Barbados,123,18,12,13,11,16,11,8,284.996,3.408,0,75.906,–,91.0225
20,Belarus,164,15,4,4,3,12,3,2,9480.04,114.344,0,72.926,99.6171,95.3602
21,Belgium,164,10,4,4,4,8,3,2,11358.4,128.957,1,81.134,–,98.9478
22,Belize,106,39,15,16,13,32,13,10,366.954,8.181,0,70.384,–,96.1412
23,Benin,7,178,98,102,93,107,63,31,10872.3,396.613,38,60.907,32.9488,95.8666
24,Bhutan,66,128,32,36,29,90,27,18,797.765,14.528,0,70.197,57.0336,85.5824
25,Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,10887.9,252.768,9,69.125,92.4551,88.4827
26,Bosnia and Herzegovina,153,18,6,7,5,16,5,5,3516.82,32.523,0,76.911,96.9918,–
27,Botswana,56,54,41,44,37,42,33,26,2250.26,53.332,2,66.797,81.1887,91.0209
28,Brazil,106,64,15,16,14,53,14,8,207653,2965.62,45,75.509,91.7294,92.6971
29,British Virgin Islands,–,–,–,–,–,–,–,–,30.661,–,–,–,–,–
30,Brunei Darussalam,131,13,10,11,9,10,9,4,423.196,6.73,0,77.203,96.0856,–
31,Bulgaria,142,18,8,8,7,15,7,4,7131.49,66.913,1,74.749,98.3525,93.3048
32,Burkina Faso,16,199,85,89,80,99,53,26,18646.4,715.598,60,60.361,34.5994,69.0963
33,Burundi,23,170,72,77,66,103,48,24,10524.1,437.227,31,57.481,61.5697,94.1483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,Sweden,179,7,3,3,3,6,2,2,9837.53,118.513,0,82.462,–,99.3731
177,Switzerland,164,8,4,4,4,7,4,3,8401.74,86.328,0,83.308,–,93.3163
178,Syrian Arab Republic,95,37,18,19,16,30,14,9,18430.5,426.666,7,70.31,80.8445,66.6641
179,Tajikistan,53,107,43,48,38,84,37,20,8734.95,250.673,11,71.051,99.4507,97.7278
180,Thailand,123,38,12,14,11,31,11,7,68863.5,725.666,9,75.303,92.8683,90.7559
181,The former Yugoslav Republic of Macedonia,123,37,12,13,11,34,11,8,2081.21,23.493,0,75.703,96.1289,91.0574
182,Timor–Leste,46,175,50,54,46,132,42,22,1268.67,44.03,2,68.881,58.309,95.5923
183,Togo,21,145,76,82,70,89,51,26,7606.37,256.286,19,60.232,63.7456,95.4313
184,Tokelau,–,–,–,–,–,–,–,–,1.282,–,–,–,–,–
185,Tonga,100,22,16,15,18,19,14,7,107.122,2.607,0,73.029,99.3855,88.2331
186,Trinidad and Tobago,92,30,19,20,17,26,17,13,1364.96,18.951,0,70.673,–,95.2379
187,Tunisia,114,57,14,15,12,44,12,8,11403.2,210.021,3,75.731,79.0364,98.5652
188,Turkey,118,74,13,13,12,56,11,7,79512.4,1294.09,16,75.755,95.6014,94.1381
189,Turkmenistan,44,86,51,60,42,70,43,22,5662.54,144.35,7,67.835,–,–
190,Turks and Caicos Islands,–,–,–,–,–,–,–,–,34.9,–,–,–,–,–
191,Tuvalu,78,57,25,28,23,44,21,17,11.097,–,0,–,–,84.4011
192,Uganda,43,175,53,58,48,104,38,21,41488,1715.49,90,59.889,70.1982,93.6503
193,Ukraine,133,19,9,10,8,17,8,5,44438.6,479.168,4,71.96,99.9744,96.1755
194,United Arab Emirates,142,17,8,9,7,14,7,4,9269.61,91.583,1,77.256,90.0339,93.375
195,United Kingdom,164,9,4,5,4,8,4,3,65788.6,805.499,3,81.565,–,99.8543
196,United Republic of Tanzania,36,179,57,60,53,108,40,22,55572.2,2086.73,117,65.675,77.8872,80.0905
197,United States,151,11,7,7,6,9,6,4,322180,4002.52,26,79.392,–,93.7542
198,Uruguay,133,23,9,10,8,21,8,5,3444.01,48.546,0,77.493,98.5239,94.2177
199,Uzbekistan,80,72,24,27,21,59,21,14,31446.8,663.073,16,71.314,99.9838,94.6949
200,Vanuatu,73,36,28,30,25,29,23,12,270.402,6.93,0,72.133,74,85.8138
201,Venezuela (Bolivarian Republic of),100,30,16,18,15,25,14,10,31568.2,602.103,10,74.545,97.1271,89.8568
202,Viet Nam,82,51,22,25,18,37,17,12,94569.1,1581.76,34,76.253,93.5204,97.9651
203,Yemen,38,126,55,59,51,88,43,27,27584.2,867.303,48,64.953,–,84.8373
204,Zambia,33,182,63,68,58,110,44,23,16591.4,620.261,39,61.874,83.0077,87.4041
205,Zimbabwe,37,75,56,62,51,50,40,23,16150.4,535.37,30,61.163,88.6934,85.8624

Then, setting the country names as row indices using set_index [function](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.set_index.html).

In [8]:
df = df.set_index(df['TABLE 1. BASIC INDICATORS'].values)
df

,TABLE 1. BASIC INDICATORS,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 16
Afghanistan,Afghanistan,25,177,70,74,66,120,53,40,34656,1142.96,80,63.673,31.7411,–
Albania,Albania,114,40,14,15,12,35,12,6,2926.35,34.75,0,78.345,97.247,95.5173
Algeria,Algeria,78,49,25,27,24,41,22,16,40606.1,949.277,24,76.078,75.136,97.0622
Andorra,Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,–
Angola,Angola,17,221,83,88,76,131,55,29,28813.5,1180.97,96,61.547,66.0301,84.0123
Anguilla,Anguilla,–,–,–,–,–,–,–,–,14.764,–,–,–,–,–
Antigua and Barbuda,Antigua and Barbuda,133,26,9,9,8,25,5,4,100.963,1.636,0,76.364,98.95,87.0461
Argentina,Argentina,126,29,11,12,10,26,10,6,43847.4,753.646,8,76.577,98.09,99.3468
Armenia,Armenia,118,50,13,15,12,42,12,7,2924.82,40.158,1,74.618,99.7444,96.0743
Australia,Australia,164,9,4,4,3,8,3,2,24125.8,310.703,1,82.896,–,97.0328
Austria,Austria,164,10,4,4,3,8,3,2,8712.14,83.099,0,81.594,–,–
Azerbaijan,Azerbaijan,68,95,31,34,28,75,27,18,9725.38,176.026,5,72.026,99.7901,94.1427
Bahamas,Bahamas,126,24,11,11,10,20,9,6,391.232,5.57,0,75.675,–,97.5202
Bahrain,Bahrain,142,23,8,8,7,20,7,3,1425.17,21.489,0,76.9,94.5568,96.4285
Bangladesh,Bangladesh,62,144,34,37,32,100,28,20,162952,3109.72,106,72.489,72.7587,90.5086
Barbados,Barbados,123,18,12,13,11,16,11,8,284.996,3.408,0,75.906,–,91.0225
Belarus,Belarus,164,15,4,4,3,12,3,2,9480.04,114.344,0,72.926,99.6171,95.3602
Belgium,Belgium,164,10,4,4,4,8,3,2,11358.4,128.957,1,81.134,–,98.9478
Belize,Belize,106,39,15,16,13,32,13,10,366.954,8.181,0,70.384,–,96.1412
Benin,Benin,7,178,98,102,93,107,63,31,10872.3,396.613,38,60.907,32.9488,95.8666
Bhutan,Bhutan,66,128,32,36,29,90,27,18,797.765,14.528,0,70.197,57.0336,85.5824
Bolivia (Plurinational State of),Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,10887.9,252.768,9,69.125,92.4551,88.4827
Bosnia and Herzegovina,Bosnia and Herzegovina,153,18,6,7,5,16,5,5,3516.82,32.523,0,76.911,96.9918,–
Botswana,Botswana,56,54,41,44,37,42,33,26,2250.26,53.332,2,66.797,81.1887,91.0209
Brazil,Brazil,106,64,15,16,14,53,14,8,207653,2965.62,45,75.509,91.7294,92.6971
British Virgin Islands,British Virgin Islands,–,–,–,–,–,–,–,–,30.661,–,–,–,–,–
Brunei Darussalam,Brunei Darussalam,131,13,10,11,9,10,9,4,423.196,6.73,0,77.203,96.0856,–
Bulgaria,Bulgaria,142,18,8,8,7,15,7,4,7131.49,66.913,1,74.749,98.3525,93.3048
Burkina Faso,Burkina Faso,16,199,85,89,80,99,53,26,18646.4,715.598,60,60.361,34.5994,69.0963
Burundi,Burundi,23,170,72,77,66,103,48,24,10524.1,437.227,31,57.481,61.5697,94.1483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweden,Sweden,179,7,3,3,3,6,2,2,9837.53,118.513,0,82.462,–,99.3731
Switzerland,Switzerland,164,8,4,4,4,7,4,3,8401.74,86.328,0,83.308,–,93.3163
Syrian Arab Republic,Syrian Arab Republic,95,37,18,19,16,30,14,9,18430.5,426.666,7,70.31,80.8445,66.6641
Tajikistan,Tajikistan,53,107,43,48,38,84,37,20,8734.95,250.673,11,71.051,99.4507,97.7278
Thailand,Thailand,123,38,12,14,11,31,11,7,68863.5,725.666,9,75.303,92.8683,90.7559
The former Yugoslav Republic of Macedonia,The former Yugoslav Republic of Macedonia,123,37,12,13,11,34,11,8,2081.21,23.493,0,75.703,96.1289,91.0574
Timor–Leste,Timor–Leste,46,175,50,54,46,132,42,22,1268.67,44.03,2,68.881,58.309,95.5923
Togo,Togo,21,145,76,82,70,89,51,26,7606.37,256.286,19,60.232,63.7456,95.4313
Tokelau,Tokelau,–,–,–,–,–,–,–,–,1.282,–,–,–,–,–
Tonga,Tonga,100,22,16,15,18,19,14,7,107.122,2.607,0,73.029,99.3855,88.2331
Trinidad and Tobago,Trinidad and Tobago,92,30,19,20,17,26,17,13,1364.96,18.951,0,70.673,–,95.2379
Tunisia,Tunisia,114,57,14,15,12,44,12,8,11403.2,210.021,3,75.731,79.0364,98.5652
Turkey,Turkey,118,74,13,13,12,56,11,7,79512.4,1294.09,16,75.755,95.6014,94.1381
Turkmenistan,Turkmenistan,44,86,51,60,42,70,43,22,5662.54,144.35,7,67.835,–,–
Turks and Caicos Islands,Turks and Caicos Islands,–,–,–,–,–,–,–,–,34.9,–,–,–,–,–
Tuvalu,Tuvalu,78,57,25,28,23,44,21,17,11.097,–,0,–,–,84.4011
Uganda,Uganda,43,175,53,58,48,104,38,21,41488,1715.49,90,59.889,70.1982,93.6503
Ukraine,Ukraine,133,19,9,10,8,17,8,5,44438.6,479.168,4,71.96,99.9744,96.1755
United Arab Emirates,United Arab Emirates,142,17,8,9,7,14,7,4,9269.61,91.583,1,77.256,90.0339,93.375
United Kingdom,United Kingdom,164,9,4,5,4,8,4,3,65788.6,805.499,3,81.565,–,99.8543
United Republic of Tanzania,United Republic of Tanzania,36,179,57,60,53,108,40,22,55572.2,2086.73,117,65.675,77.8872,80.0905
United States,United States,151,11,7,7,6,9,6,4,322180,4002.52,26,79.392,–,93.7542
Uruguay,Uruguay,133,23,9,10,8,21,8,5,3444.01,48.546,0,77.493,98.5239,94.2177
Uzbekistan,Uzbekistan,80,72,24,27,21,59,21,14,31446.8,663.073,16,71.314,99.9838,94.6949
Vanuatu,Vanuatu,73,36,28,30,25,29,23,12,270.402,6.93,0,72.133,74,85.8138
Venezuela (Bolivarian Republic of),Venezuela (Bolivarian Republic of),100,30,16,18,15,25,14,10,31568.2,602.103,10,74.545,97.1271,89.8568
Viet Nam,Viet Nam,82,51,22,25,18,37,17,12,94569.1,1581.76,34,76.253,93.5204,97.9651
Yemen,Yemen,38,126,55,59,51,88,43,27,27584.2,867.303,48,64.953,–,84.8373
Zambia,Zambia,33,182,63,68,58,110,44,23,16591.4,620.261,39,61.874,83.0077,87.4041
Zimbabwe,Zimbabwe,37,75,56,62,51,50,40,23,16150.4,535.37,30,61.163,88.6934,85.8624

Deleting the redundant column.

In [9]:
df = df.drop('TABLE 1. BASIC INDICATORS', 1)
df

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 16
Afghanistan,25,177,70,74,66,120,53,40,34656,1142.96,80,63.673,31.7411,–
Albania,114,40,14,15,12,35,12,6,2926.35,34.75,0,78.345,97.247,95.5173
Algeria,78,49,25,27,24,41,22,16,40606.1,949.277,24,76.078,75.136,97.0622
Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,–
Angola,17,221,83,88,76,131,55,29,28813.5,1180.97,96,61.547,66.0301,84.0123
Anguilla,–,–,–,–,–,–,–,–,14.764,–,–,–,–,–
Antigua and Barbuda,133,26,9,9,8,25,5,4,100.963,1.636,0,76.364,98.95,87.0461
Argentina,126,29,11,12,10,26,10,6,43847.4,753.646,8,76.577,98.09,99.3468
Armenia,118,50,13,15,12,42,12,7,2924.82,40.158,1,74.618,99.7444,96.0743
Australia,164,9,4,4,3,8,3,2,24125.8,310.703,1,82.896,–,97.0328
Austria,164,10,4,4,3,8,3,2,8712.14,83.099,0,81.594,–,–
Azerbaijan,68,95,31,34,28,75,27,18,9725.38,176.026,5,72.026,99.7901,94.1427
Bahamas,126,24,11,11,10,20,9,6,391.232,5.57,0,75.675,–,97.5202
Bahrain,142,23,8,8,7,20,7,3,1425.17,21.489,0,76.9,94.5568,96.4285
Bangladesh,62,144,34,37,32,100,28,20,162952,3109.72,106,72.489,72.7587,90.5086
Barbados,123,18,12,13,11,16,11,8,284.996,3.408,0,75.906,–,91.0225
Belarus,164,15,4,4,3,12,3,2,9480.04,114.344,0,72.926,99.6171,95.3602
Belgium,164,10,4,4,4,8,3,2,11358.4,128.957,1,81.134,–,98.9478
Belize,106,39,15,16,13,32,13,10,366.954,8.181,0,70.384,–,96.1412
Benin,7,178,98,102,93,107,63,31,10872.3,396.613,38,60.907,32.9488,95.8666
Bhutan,66,128,32,36,29,90,27,18,797.765,14.528,0,70.197,57.0336,85.5824
Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,10887.9,252.768,9,69.125,92.4551,88.4827
Bosnia and Herzegovina,153,18,6,7,5,16,5,5,3516.82,32.523,0,76.911,96.9918,–
Botswana,56,54,41,44,37,42,33,26,2250.26,53.332,2,66.797,81.1887,91.0209
Brazil,106,64,15,16,14,53,14,8,207653,2965.62,45,75.509,91.7294,92.6971
British Virgin Islands,–,–,–,–,–,–,–,–,30.661,–,–,–,–,–
Brunei Darussalam,131,13,10,11,9,10,9,4,423.196,6.73,0,77.203,96.0856,–
Bulgaria,142,18,8,8,7,15,7,4,7131.49,66.913,1,74.749,98.3525,93.3048
Burkina Faso,16,199,85,89,80,99,53,26,18646.4,715.598,60,60.361,34.5994,69.0963
Burundi,23,170,72,77,66,103,48,24,10524.1,437.227,31,57.481,61.5697,94.1483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweden,179,7,3,3,3,6,2,2,9837.53,118.513,0,82.462,–,99.3731
Switzerland,164,8,4,4,4,7,4,3,8401.74,86.328,0,83.308,–,93.3163
Syrian Arab Republic,95,37,18,19,16,30,14,9,18430.5,426.666,7,70.31,80.8445,66.6641
Tajikistan,53,107,43,48,38,84,37,20,8734.95,250.673,11,71.051,99.4507,97.7278
Thailand,123,38,12,14,11,31,11,7,68863.5,725.666,9,75.303,92.8683,90.7559
The former Yugoslav Republic of Macedonia,123,37,12,13,11,34,11,8,2081.21,23.493,0,75.703,96.1289,91.0574
Timor–Leste,46,175,50,54,46,132,42,22,1268.67,44.03,2,68.881,58.309,95.5923
Togo,21,145,76,82,70,89,51,26,7606.37,256.286,19,60.232,63.7456,95.4313
Tokelau,–,–,–,–,–,–,–,–,1.282,–,–,–,–,–
Tonga,100,22,16,15,18,19,14,7,107.122,2.607,0,73.029,99.3855,88.2331
Trinidad and Tobago,92,30,19,20,17,26,17,13,1364.96,18.951,0,70.673,–,95.2379
Tunisia,114,57,14,15,12,44,12,8,11403.2,210.021,3,75.731,79.0364,98.5652
Turkey,118,74,13,13,12,56,11,7,79512.4,1294.09,16,75.755,95.6014,94.1381
Turkmenistan,44,86,51,60,42,70,43,22,5662.54,144.35,7,67.835,–,–
Turks and Caicos Islands,–,–,–,–,–,–,–,–,34.9,–,–,–,–,–
Tuvalu,78,57,25,28,23,44,21,17,11.097,–,0,–,–,84.4011
Uganda,43,175,53,58,48,104,38,21,41488,1715.49,90,59.889,70.1982,93.6503
Ukraine,133,19,9,10,8,17,8,5,44438.6,479.168,4,71.96,99.9744,96.1755
United Arab Emirates,142,17,8,9,7,14,7,4,9269.61,91.583,1,77.256,90.0339,93.375
United Kingdom,164,9,4,5,4,8,4,3,65788.6,805.499,3,81.565,–,99.8543
United Republic of Tanzania,36,179,57,60,53,108,40,22,55572.2,2086.73,117,65.675,77.8872,80.0905
United States,151,11,7,7,6,9,6,4,322180,4002.52,26,79.392,–,93.7542
Uruguay,133,23,9,10,8,21,8,5,3444.01,48.546,0,77.493,98.5239,94.2177
Uzbekistan,80,72,24,27,21,59,21,14,31446.8,663.073,16,71.314,99.9838,94.6949
Vanuatu,73,36,28,30,25,29,23,12,270.402,6.93,0,72.133,74,85.8138
Venezuela (Bolivarian Republic of),100,30,16,18,15,25,14,10,31568.2,602.103,10,74.545,97.1271,89.8568
Viet Nam,82,51,22,25,18,37,17,12,94569.1,1581.76,34,76.253,93.5204,97.9651
Yemen,38,126,55,59,51,88,43,27,27584.2,867.303,48,64.953,–,84.8373
Zambia,33,182,63,68,58,110,44,23,16591.4,620.261,39,61.874,83.0077,87.4041
Zimbabwe,37,75,56,62,51,50,40,23,16150.4,535.37,30,61.163,88.6934,85.8624

Reindexing all columns.

In [10]:
df.columns = list(range(len(df.columns))) 
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
Afghanistan,25,177,70,74,66,120,53,40,34656,1142.96,80,63.673,31.7411,–
Albania,114,40,14,15,12,35,12,6,2926.35,34.75,0,78.345,97.247,95.5173
Algeria,78,49,25,27,24,41,22,16,40606.1,949.277,24,76.078,75.136,97.0622
Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,–
Angola,17,221,83,88,76,131,55,29,28813.5,1180.97,96,61.547,66.0301,84.0123

Setting the index name.

In [11]:
df.index.names = ['Country Name']
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
Country Name,,,,,,,,,,,,,,
Afghanistan,25,177,70,74,66,120,53,40,34656,1142.96,80,63.673,31.7411,–
Albania,114,40,14,15,12,35,12,6,2926.35,34.75,0,78.345,97.247,95.5173
Algeria,78,49,25,27,24,41,22,16,40606.1,949.277,24,76.078,75.136,97.0622
Andorra,179,9,3,3,3,7,2,1,77.281,–,0,–,100,–
Angola,17,221,83,88,76,131,55,29,28813.5,1180.97,96,61.547,66.0301,84.0123
Anguilla,–,–,–,–,–,–,–,–,14.764,–,–,–,–,–
Antigua and Barbuda,133,26,9,9,8,25,5,4,100.963,1.636,0,76.364,98.95,87.0461
Argentina,126,29,11,12,10,26,10,6,43847.4,753.646,8,76.577,98.09,99.3468
Armenia,118,50,13,15,12,42,12,7,2924.82,40.158,1,74.618,99.7444,96.0743
Australia,164,9,4,4,3,8,3,2,24125.8,310.703,1,82.896,–,97.0328
Austria,164,10,4,4,3,8,3,2,8712.14,83.099,0,81.594,–,–
Azerbaijan,68,95,31,34,28,75,27,18,9725.38,176.026,5,72.026,99.7901,94.1427
Bahamas,126,24,11,11,10,20,9,6,391.232,5.57,0,75.675,–,97.5202
Bahrain,142,23,8,8,7,20,7,3,1425.17,21.489,0,76.9,94.5568,96.4285
Bangladesh,62,144,34,37,32,100,28,20,162952,3109.72,106,72.489,72.7587,90.5086
Barbados,123,18,12,13,11,16,11,8,284.996,3.408,0,75.906,–,91.0225
Belarus,164,15,4,4,3,12,3,2,9480.04,114.344,0,72.926,99.6171,95.3602
Belgium,164,10,4,4,4,8,3,2,11358.4,128.957,1,81.134,–,98.9478
Belize,106,39,15,16,13,32,13,10,366.954,8.181,0,70.384,–,96.1412
Benin,7,178,98,102,93,107,63,31,10872.3,396.613,38,60.907,32.9488,95.8666
Bhutan,66,128,32,36,29,90,27,18,797.765,14.528,0,70.197,57.0336,85.5824
Bolivia (Plurinational State of),58,124,37,40,33,85,30,19,10887.9,252.768,9,69.125,92.4551,88.4827
Bosnia and Herzegovina,153,18,6,7,5,16,5,5,3516.82,32.523,0,76.911,96.9918,–
Botswana,56,54,41,44,37,42,33,26,2250.26,53.332,2,66.797,81.1887,91.0209
Brazil,106,64,15,16,14,53,14,8,207653,2965.62,45,75.509,91.7294,92.6971
British Virgin Islands,–,–,–,–,–,–,–,–,30.661,–,–,–,–,–
Brunei Darussalam,131,13,10,11,9,10,9,4,423.196,6.73,0,77.203,96.0856,–
Bulgaria,142,18,8,8,7,15,7,4,7131.49,66.913,1,74.749,98.3525,93.3048
Burkina Faso,16,199,85,89,80,99,53,26,18646.4,715.598,60,60.361,34.5994,69.0963
Burundi,23,170,72,77,66,103,48,24,10524.1,437.227,31,57.481,61.5697,94.1483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweden,179,7,3,3,3,6,2,2,9837.53,118.513,0,82.462,–,99.3731
Switzerland,164,8,4,4,4,7,4,3,8401.74,86.328,0,83.308,–,93.3163
Syrian Arab Republic,95,37,18,19,16,30,14,9,18430.5,426.666,7,70.31,80.8445,66.6641
Tajikistan,53,107,43,48,38,84,37,20,8734.95,250.673,11,71.051,99.4507,97.7278
Thailand,123,38,12,14,11,31,11,7,68863.5,725.666,9,75.303,92.8683,90.7559
The former Yugoslav Republic of Macedonia,123,37,12,13,11,34,11,8,2081.21,23.493,0,75.703,96.1289,91.0574
Timor–Leste,46,175,50,54,46,132,42,22,1268.67,44.03,2,68.881,58.309,95.5923
Togo,21,145,76,82,70,89,51,26,7606.37,256.286,19,60.232,63.7456,95.4313
Tokelau,–,–,–,–,–,–,–,–,1.282,–,–,–,–,–
Tonga,100,22,16,15,18,19,14,7,107.122,2.607,0,73.029,99.3855,88.2331
Trinidad and Tobago,92,30,19,20,17,26,17,13,1364.96,18.951,0,70.673,–,95.2379
Tunisia,114,57,14,15,12,44,12,8,11403.2,210.021,3,75.731,79.0364,98.5652
Turkey,118,74,13,13,12,56,11,7,79512.4,1294.09,16,75.755,95.6014,94.1381
Turkmenistan,44,86,51,60,42,70,43,22,5662.54,144.35,7,67.835,–,–
Turks and Caicos Islands,–,–,–,–,–,–,–,–,34.9,–,–,–,–,–
Tuvalu,78,57,25,28,23,44,21,17,11.097,–,0,–,–,84.4011
Uganda,43,175,53,58,48,104,38,21,41488,1715.49,90,59.889,70.1982,93.6503
Ukraine,133,19,9,10,8,17,8,5,44438.6,479.168,4,71.96,99.9744,96.1755
United Arab Emirates,142,17,8,9,7,14,7,4,9269.61,91.583,1,77.256,90.0339,93.375
United Kingdom,164,9,4,5,4,8,4,3,65788.6,805.499,3,81.565,–,99.8543
United Republic of Tanzania,36,179,57,60,53,108,40,22,55572.2,2086.73,117,65.675,77.8872,80.0905
United States,151,11,7,7,6,9,6,4,322180,4002.52,26,79.392,–,93.7542
Uruguay,133,23,9,10,8,21,8,5,3444.01,48.546,0,77.493,98.5239,94.2177
Uzbekistan,80,72,24,27,21,59,21,14,31446.8,663.073,16,71.314,99.9838,94.6949
Vanuatu,73,36,28,30,25,29,23,12,270.402,6.93,0,72.133,74,85.8138
Venezuela (Bolivarian Republic of),100,30,16,18,15,25,14,10,31568.2,602.103,10,74.545,97.1271,89.8568
Viet Nam,82,51,22,25,18,37,17,12,94569.1,1581.76,34,76.253,93.5204,97.9651
Yemen,38,126,55,59,51,88,43,27,27584.2,867.303,48,64.953,–,84.8373
Zambia,33,182,63,68,58,110,44,23,16591.4,620.261,39,61.874,83.0077,87.4041
Zimbabwe,37,75,56,62,51,50,40,23,16150.4,535.37,30,61.163,88.6934,85.8624

By far, the number of rows and columns(202*14) is meet the requirement of this task. 

According to the sample figure, the **"–"** should be replaced as [**"NaN"**](https://chrisalbon.com/python/data_wrangling/pandas_replace_values/).

In [12]:
df = df.replace('–',np.nan)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
Country Name,,,,,,,,,,,,,,
Afghanistan,25.0,177.0,70.0,74.0,66.0,120.0,53.0,40.0,34656.032,1142.962,80.0,63.673,31.74112,NaN
Albania,114.0,40.0,14.0,15.0,12.0,35.0,12.0,6.0,2926.348,34.750,0.0,78.345,97.24697,95.51731
Algeria,78.0,49.0,25.0,27.0,24.0,41.0,22.0,16.0,40606.052,949.277,24.0,76.078,75.13605,97.06215
Andorra,179.0,9.0,3.0,3.0,3.0,7.0,2.0,1.0,77.281,NaN,0.0,NaN,100.00000,NaN
Angola,17.0,221.0,83.0,88.0,76.0,131.0,55.0,29.0,28813.463,1180.970,96.0,61.547,66.03011,84.01231
Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.764,NaN,NaN,NaN,NaN,NaN
Antigua and Barbuda,133.0,26.0,9.0,9.0,8.0,25.0,5.0,4.0,100.963,1.636,0.0,76.364,98.95000,87.04613
Argentina,126.0,29.0,11.0,12.0,10.0,26.0,10.0,6.0,43847.430,753.646,8.0,76.577,98.09000,99.34679
Armenia,118.0,50.0,13.0,15.0,12.0,42.0,12.0,7.0,2924.816,40.158,1.0,74.618,99.74441,96.07425
Australia,164.0,9.0,4.0,4.0,3.0,8.0,3.0,2.0,24125.848,310.703,1.0,82.896,NaN,97.03283
Austria,164.0,10.0,4.0,4.0,3.0,8.0,3.0,2.0,8712.137,83.099,0.0,81.594,NaN,NaN
Azerbaijan,68.0,95.0,31.0,34.0,28.0,75.0,27.0,18.0,9725.376,176.026,5.0,72.026,99.79006,94.14265
Bahamas,126.0,24.0,11.0,11.0,10.0,20.0,9.0,6.0,391.232,5.570,0.0,75.675,NaN,97.52022
Bahrain,142.0,23.0,8.0,8.0,7.0,20.0,7.0,3.0,1425.171,21.489,0.0,76.900,94.55679,96.42850
Bangladesh,62.0,144.0,34.0,37.0,32.0,100.0,28.0,20.0,162951.560,3109.722,106.0,72.489,72.75872,90.50861
Barbados,123.0,18.0,12.0,13.0,11.0,16.0,11.0,8.0,284.996,3.408,0.0,75.906,NaN,91.02247
Belarus,164.0,15.0,4.0,4.0,3.0,12.0,3.0,2.0,9480.042,114.344,0.0,72.926,99.61706,95.36020
Belgium,164.0,10.0,4.0,4.0,4.0,8.0,3.0,2.0,11358.379,128.957,1.0,81.134,NaN,98.94778
Belize,106.0,39.0,15.0,16.0,13.0,32.0,13.0,10.0,366.954,8.181,0.0,70.384,NaN,96.14116
Benin,7.0,178.0,98.0,102.0,93.0,107.0,63.0,31.0,10872.298,396.613,38.0,60.907,32.94882,95.86662
Bhutan,66.0,128.0,32.0,36.0,29.0,90.0,27.0,18.0,797.765,14.528,0.0,70.197,57.03360,85.58240
Bolivia (Plurinational State of),58.0,124.0,37.0,40.0,33.0,85.0,30.0,19.0,10887.882,252.768,9.0,69.125,92.45508,88.48272
Bosnia and Herzegovina,153.0,18.0,6.0,7.0,5.0,16.0,5.0,5.0,3516.816,32.523,0.0,76.911,96.99177,NaN
Botswana,56.0,54.0,41.0,44.0,37.0,42.0,33.0,26.0,2250.260,53.332,2.0,66.797,81.18871,91.02086
Brazil,106.0,64.0,15.0,16.0,14.0,53.0,14.0,8.0,207652.865,2965.624,45.0,75.509,91.72943,92.69713
British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.661,NaN,NaN,NaN,NaN,NaN
Brunei Darussalam,131.0,13.0,10.0,11.0,9.0,10.0,9.0,4.0,423.196,6.730,0.0,77.203,96.08556,NaN
Bulgaria,142.0,18.0,8.0,8.0,7.0,15.0,7.0,4.0,7131.494,66.913,1.0,74.749,98.35245,93.30484
Burkina Faso,16.0,199.0,85.0,89.0,80.0,99.0,53.0,26.0,18646.433,715.598,60.0,60.361,34.59940,69.09631
Burundi,23.0,170.0,72.0,77.0,66.0,103.0,48.0,24.0,10524.117,437.227,31.0,57.481,61.56973,94.14828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweden,179.0,7.0,3.0,3.0,3.0,6.0,2.0,2.0,9837.533,118.513,0.0,82.462,NaN,99.37306
Switzerland,164.0,8.0,4.0,4.0,4.0,7.0,4.0,3.0,8401.739,86.328,0.0,83.308,NaN,93.31632
Syrian Arab Republic,95.0,37.0,18.0,19.0,16.0,30.0,14.0,9.0,18430.453,426.666,7.0,70.310,80.84452,66.66408
Tajikistan,53.0,107.0,43.0,48.0,38.0,84.0,37.0,20.0,8734.951,250.673,11.0,71.051,99.45068,97.72782
Thailand,123.0,38.0,12.0,14.0,11.0,31.0,11.0,7.0,68863.514,725.666,9.0,75.303,92.86831,90.75587
The former Yugoslav Republic of Macedonia,123.0,37.0,12.0,13.0,11.0,34.0,11.0,8.0,2081.206,23.493,0.0,75.703,96.12893,91.05736
Timor–Leste,46.0,175.0,50.0,54.0,46.0,132.0,42.0,22.0,1268.671,44.030,2.0,68.881,58.30898,95.59233
Togo,21.0,145.0,76.0,82.0,70.0,89.0,51.0,26.0,7606.374,256.286,19.0,60.232,63.74562,95.43129
Tokelau,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.282,NaN,NaN,NaN,NaN,NaN
Tonga,100.0,22.0,16.0,15.0,18.0,19.0,14.0,7.0,107.122,2.607,0.0,73.029,99.38553,88.23308
Trinidad and Tobago,92.0,30.0,19.0,20.0,17.0,26.0,17.0,13.0,1364.962,18.951,0.0,70.673,NaN,95.23794
Tunisia,114.0,57.0,14.0,15.0,12.0,44.0,12.0,8.0,11403.248,210.021,3.0,75.731,79.03643,98.56518
Turkey,118.0,74.0,13.0,13.0,12.0,56.0,11.0,7.0,79512.426,1294.085,16.0,75.755,95.60142,94.13807
Turkmenistan,44.0,86.0,51.0,60.0,42.0,70.0,43.0,22.0,5662.544,144.350,7.0,67.835,NaN,NaN
Turks and Caicos Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.900,NaN,NaN,NaN,NaN,NaN
Tuvalu,78.0,57.0,25.0,28.0,23.0,44.0,21.0,17.0,11.097,NaN,0.0,NaN,NaN,84.40111
Uganda,43.0,175.0,53.0,58.0,48.0,104.0,38.0,21.0,41487.965,1715.486,90.0,59.889,70.19822,93.65028
Ukraine,133.0,19.0,9.0,10.0,8.0,17.0,8.0,5.0,44438.625,479.168,4.0,71.960,99.97435,96.17551
United Arab Emirates,142.0,17.0,8.0,9.0,7.0,14.0,7.0,4.0,9269.612,91.583,1.0,77.256,90.03385,93.37500
United Kingdom,164.0,9.0,4.0,5.0,4.0,8.0,4.0,3.0,65788.574,805.499,3.0,81.565,NaN,99.85433
United Republic of Tanzania,36.0,179.0,57.0,60.0,53.0,108.0,40.0,22.0,55572.201,2086.732,117.0,65.675,77.88723,80.09053
United States,151.0,11.0,7.0,7.0,6.0,9.0,6.0,4.0,322179.605,4002.519,26.0,79.392,NaN,93.75419
Uruguay,133.0,23.0,9.0,10.0,8.0,21.0,8.0,5.0,3444.006,48.546,0.0,77.493,98.52387,94.21768
Uzbekistan,80.0,72.0,24.0,27.0,21.0,59.0,21.0,14.0,31446.795,663.073,16.0,71.314,99.98383,94.69494
Vanuatu,73.0,36.0,28.0,30.0,25.0,29.0,23.0,12.0,270.402,6.930,0.0,72.133,74.00000,85.81376
Venezuela (Bolivarian Republic of),100.0,30.0,16.0,18.0,15.0,25.0,14.0,10.0,31568.179,602.103,10.0,74.545,97.12709,89.85675
Viet Nam,82.0,51.0,22.0,25.0,18.0,37.0,17.0,12.0,94569.072,1581.762,34.0,76.253,93.52045,97.96511
Yemen,38.0,126.0,55.0,59.0,51.0,88.0,43.0,27.0,27584.213,867.303,48.0,64.953,NaN,84.83733
Zambia,33.0,182.0,63.0,68.0,58.0,110.0,44.0,23.0,16591.390,620.261,39.0,61.874,83.00767,87.40411
Zimbabwe,37.0,75.0,56.0,62.0,51.0,50.0,40.0,23.0,16150.362,535.370,30.0,61.163,88.69342,85.86239

And we can notice that the data in DataFrame is float and in csv they should be stored as integer, so we need to set the float_format as '%.0f'(which means no decimal). Furthermore, some countries' name may not be written in English character, so setting [`encoding = 'utf-16'`]() will be more reasonable and the `sep = '\t'` is added accordingly.

In [13]:
df.to_csv('basic_indicators.csv', float_format='%.0f', encoding = 'utf-16',sep = '\t')

We can load the exported CSV file to check the result.

In [14]:
csv_data = pd.read_csv('basic_indicators.csv',encoding = 'utf-16',sep = '\t')
csv_data

,Country Name,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Afghanistan,25.0,177.0,70.0,74.0,66.0,120.0,53.0,40.0,34656,1143.0,80.0,64.0,32.0,NaN
1,Albania,114.0,40.0,14.0,15.0,12.0,35.0,12.0,6.0,2926,35.0,0.0,78.0,97.0,96.0
2,Algeria,78.0,49.0,25.0,27.0,24.0,41.0,22.0,16.0,40606,949.0,24.0,76.0,75.0,97.0
3,Andorra,179.0,9.0,3.0,3.0,3.0,7.0,2.0,1.0,77,NaN,0.0,NaN,100.0,NaN
4,Angola,17.0,221.0,83.0,88.0,76.0,131.0,55.0,29.0,28813,1181.0,96.0,62.0,66.0,84.0
5,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN
6,Antigua and Barbuda,133.0,26.0,9.0,9.0,8.0,25.0,5.0,4.0,101,2.0,0.0,76.0,99.0,87.0
7,Argentina,126.0,29.0,11.0,12.0,10.0,26.0,10.0,6.0,43847,754.0,8.0,77.0,98.0,99.0
8,Armenia,118.0,50.0,13.0,15.0,12.0,42.0,12.0,7.0,2925,40.0,1.0,75.0,100.0,96.0
9,Australia,164.0,9.0,4.0,4.0,3.0,8.0,3.0,2.0,24126,311.0,1.0,83.0,NaN,97.0
10,Austria,164.0,10.0,4.0,4.0,3.0,8.0,3.0,2.0,8712,83.0,0.0,82.0,NaN,NaN
11,Azerbaijan,68.0,95.0,31.0,34.0,28.0,75.0,27.0,18.0,9725,176.0,5.0,72.0,100.0,94.0
12,Bahamas,126.0,24.0,11.0,11.0,10.0,20.0,9.0,6.0,391,6.0,0.0,76.0,NaN,98.0
13,Bahrain,142.0,23.0,8.0,8.0,7.0,20.0,7.0,3.0,1425,21.0,0.0,77.0,95.0,96.0
14,Bangladesh,62.0,144.0,34.0,37.0,32.0,100.0,28.0,20.0,162952,3110.0,106.0,72.0,73.0,91.0
15,Barbados,123.0,18.0,12.0,13.0,11.0,16.0,11.0,8.0,285,3.0,0.0,76.0,NaN,91.0
16,Belarus,164.0,15.0,4.0,4.0,3.0,12.0,3.0,2.0,9480,114.0,0.0,73.0,100.0,95.0
17,Belgium,164.0,10.0,4.0,4.0,4.0,8.0,3.0,2.0,11358,129.0,1.0,81.0,NaN,99.0
18,Belize,106.0,39.0,15.0,16.0,13.0,32.0,13.0,10.0,367,8.0,0.0,70.0,NaN,96.0
19,Benin,7.0,178.0,98.0,102.0,93.0,107.0,63.0,31.0,10872,397.0,38.0,61.0,33.0,96.0
20,Bhutan,66.0,128.0,32.0,36.0,29.0,90.0,27.0,18.0,798,15.0,0.0,70.0,57.0,86.0
21,Bolivia (Plurinational State of),58.0,124.0,37.0,40.0,33.0,85.0,30.0,19.0,10888,253.0,9.0,69.0,92.0,88.0
22,Bosnia and Herzegovina,153.0,18.0,6.0,7.0,5.0,16.0,5.0,5.0,3517,33.0,0.0,77.0,97.0,NaN
23,Botswana,56.0,54.0,41.0,44.0,37.0,42.0,33.0,26.0,2250,53.0,2.0,67.0,81.0,91.0
24,Brazil,106.0,64.0,15.0,16.0,14.0,53.0,14.0,8.0,207653,2966.0,45.0,76.0,92.0,93.0
25,British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,NaN,NaN,NaN,NaN,NaN
26,Brunei Darussalam,131.0,13.0,10.0,11.0,9.0,10.0,9.0,4.0,423,7.0,0.0,77.0,96.0,NaN
27,Bulgaria,142.0,18.0,8.0,8.0,7.0,15.0,7.0,4.0,7131,67.0,1.0,75.0,98.0,93.0
28,Burkina Faso,16.0,199.0,85.0,89.0,80.0,99.0,53.0,26.0,18646,716.0,60.0,60.0,35.0,69.0
29,Burundi,23.0,170.0,72.0,77.0,66.0,103.0,48.0,24.0,10524,437.0,31.0,57.0,62.0,94.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,Sweden,179.0,7.0,3.0,3.0,3.0,6.0,2.0,2.0,9838,119.0,0.0,82.0,NaN,99.0
173,Switzerland,164.0,8.0,4.0,4.0,4.0,7.0,4.0,3.0,8402,86.0,0.0,83.0,NaN,93.0
174,Syrian Arab Republic,95.0,37.0,18.0,19.0,16.0,30.0,14.0,9.0,18430,427.0,7.0,70.0,81.0,67.0
175,Tajikistan,53.0,107.0,43.0,48.0,38.0,84.0,37.0,20.0,8735,251.0,11.0,71.0,99.0,98.0
176,Thailand,123.0,38.0,12.0,14.0,11.0,31.0,11.0,7.0,68864,726.0,9.0,75.0,93.0,91.0
177,The former Yugoslav Republic of Macedonia,123.0,37.0,12.0,13.0,11.0,34.0,11.0,8.0,2081,23.0,0.0,76.0,96.0,91.0
178,Timor–Leste,46.0,175.0,50.0,54.0,46.0,132.0,42.0,22.0,1269,44.0,2.0,69.0,58.0,96.0
179,Togo,21.0,145.0,76.0,82.0,70.0,89.0,51.0,26.0,7606,256.0,19.0,60.0,64.0,95.0
180,Tokelau,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
181,Tonga,100.0,22.0,16.0,15.0,18.0,19.0,14.0,7.0,107,3.0,0.0,73.0,99.0,88.0
182,Trinidad and Tobago,92.0,30.0,19.0,20.0,17.0,26.0,17.0,13.0,1365,19.0,0.0,71.0,NaN,95.0
183,Tunisia,114.0,57.0,14.0,15.0,12.0,44.0,12.0,8.0,11403,210.0,3.0,76.0,79.0,99.0
184,Turkey,118.0,74.0,13.0,13.0,12.0,56.0,11.0,7.0,79512,1294.0,16.0,76.0,96.0,94.0
185,Turkmenistan,44.0,86.0,51.0,60.0,42.0,70.0,43.0,22.0,5663,144.0,7.0,68.0,NaN,NaN
186,Turks and Caicos Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,NaN,NaN,NaN,NaN,NaN
187,Tuvalu,78.0,57.0,25.0,28.0,23.0,44.0,21.0,17.0,11,NaN,0.0,NaN,NaN,84.0
188,Uganda,43.0,175.0,53.0,58.0,48.0,104.0,38.0,21.0,41488,1715.0,90.0,60.0,70.0,94.0
189,Ukraine,133.0,19.0,9.0,10.0,8.0,17.0,8.0,5.0,44439,479.0,4.0,72.0,100.0,96.0
190,United Arab Emirates,142.0,17.0,8.0,9.0,7.0,14.0,7.0,4.0,9270,92.0,1.0,77.0,90.0,93.0
191,United Kingdom,164.0,9.0,4.0,5.0,4.0,8.0,4.0,3.0,65789,805.0,3.0,82.0,NaN,100.0
192,United Republic of Tanzania,36.0,179.0,57.0,60.0,53.0,108.0,40.0,22.0,55572,2087.0,117.0,66.0,78.0,80.0
193,United States,151.0,11.0,7.0,7.0,6.0,9.0,6.0,4.0,322180,4003.0,26.0,79.0,NaN,94.0
194,Uruguay,133.0,23.0,9.0,10.0,8.0,21.0,8.0,5.0,3444,49.0,0.0,77.0,99.0,94.0
195,Uzbekistan,80.0,72.0,24.0,27.0,21.0,59.0,21.0,14.0,31447,663.0,16.0,71.0,100.0,95.0
196,Vanuatu,73.0,36.0,28.0,30.0,25.0,29.0,23.0,12.0,270,7.0,0.0,72.0,74.0,86.0
197,Venezuela (Bolivarian Republic of),100.0,30.0,16.0,18.0,15.0,25.0,14.0,10.0,31568,602.0,10.0,75.0,97.0,90.0
198,Viet Nam,82.0,51.0,22.0,25.0,18.0,37.0,17.0,12.0,94569,1582.0,34.0,76.0,94.0,98.0
199,Yemen,38.0,126.0,55.0,59.0,51.0,88.0,43.0,27.0,27584,867.0,48.0,65.0,NaN,85.0
200,Zambia,33.0,182.0,63.0,68.0,58.0,110.0,44.0,23.0,16591,620.0,39.0,62.0,83.0,87.0
201,Zimbabwe,37.0,75.0,56.0,62.0,51.0,50.0,40.0,23.0,16150,535.0,30.0,61.0,89.0,86.0

## 4. Summary

Excel file is easier to be parsed by Python than other kind of file since it can be load into a Pandas DataFrame directly. As Excel is a popular spreadsheet application, so in future career, there is a high chance for us to extract data from Excel and it is a must-have skill as a data wrangler.

The main outcomes achieved while completing this task were:
- Being familiar and makeing good use of Pandas DataFrame to process data.
- Before parsing any file, we need to understand the content well.

## 5. Reference

- The pandas Project. (2018). *pandas 0.22.0 documentation: IO Tools (Text, CSV, HDF5, ...).* Retrieved from: http://pandas.pydata.org/pandas-docs/stable/io.html#io-excel-reader
- The pandas Project. (2018).  *pandas 0.22.0 documentation: pandas.DataFrame.dropna.* Retrieved from: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dropna.html
- The pandas Project. (2018).  *pandas 0.22.0 documentation: pandas.DataFrame.set_index.* Retrieved from: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.set_index.html
- Chris Albon (2017 December,20) *Replacing Values In pandas* Retrived from: https://chrisalbon.com/python/data_wrangling/pandas_replace_values/
- The pandas Project. (2014).  *pandas 0.16.2 documentation: pandas.DataFrame.to_csv* Retrieved from: http://pandas.pydata.org/pandas-docs/version/0.16/generated/pandas.DataFrame.to_csv.html